apiVersion: delivery.ocm.software/v1alpha1
kind: Localization
metadata:
  name: podinfo
  namespace: ocm-system
spec:
  interval: 1m0s
  componentVersionRef:
    name: podinfo
    namespace: ocm-system
  source:
    sourceRef:
      kind: Snapshot
      name: podinfo-deployment
      namespace: ocm-system
  configRef:
    resource:
      resourceRef:
        name: config
  snapshotTemplate:
    name: podinfo-deployment-localized
    createFluxSource: true
